version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "1.4.1-absvoid"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Git submodule"
    labels:
      - "dependencies"
